//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LogCabin.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Descriptions {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Descriptions() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LogCabin.Resources.Descriptions", typeof(Descriptions).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Das ist der Dachboden..
        /// </summary>
        internal static string ATTIC {
            get {
                return ResourceManager.GetString("ATTIC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Das ist das Schlafzimmer..
        /// </summary>
        internal static string BEDROOM {
            get {
                return ResourceManager.GetString("BEDROOM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Die Verwandlung.
        /// </summary>
        internal static string BOOK_I {
            get {
                return ResourceManager.GetString("BOOK_I", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Krieg und Frieden.
        /// </summary>
        internal static string BOOK_II {
            get {
                return ResourceManager.GetString("BOOK_II", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to De Profundis.
        /// </summary>
        internal static string BOOK_III {
            get {
                return ResourceManager.GetString("BOOK_III", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Die Blechtrommel.
        /// </summary>
        internal static string BOOK_IV {
            get {
                return ResourceManager.GetString("BOOK_IV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Die Dreigroschenoper.
        /// </summary>
        internal static string BOOK_V {
            get {
                return ResourceManager.GetString("BOOK_V", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Du nimmst Dir wahllos eines der Bücher aus dem Regel. &quot;{0}&quot; - ein weiteres Meisterwerk der Weltliteratur. Mit einem Lächeln im Gesicht steckst Du es zurück an seinen Platz..
        /// </summary>
        internal static string BOOKS {
            get {
                return ResourceManager.GetString("BOOKS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ein altes Bücherregal aus Holz. Neben viel Staub stehen dort nur einige Bücher drin..
        /// </summary>
        internal static string BOOKSHELF {
            get {
                return ResourceManager.GetString("BOOKSHELF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eine große weiße Kerze, die bestimmt einige Tage brennen kann. .
        /// </summary>
        internal static string CANDLE {
            get {
                return ResourceManager.GetString("CANDLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auf dem Tisch steht eine brennende Kerze, die ein spärliches Licht in den kalten Raum wirft..
        /// </summary>
        internal static string CANDLE_CONTAINMENT {
            get {
                return ResourceManager.GetString("CANDLE_CONTAINMENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Als Du die Kerze in die Hand nimmst, fühlt sie sich schwerer an, als Du vermutet hättest. Als wäre etwas im Wachs, das dort nicht hinein gehört..
        /// </summary>
        internal static string CANDLE_PICKUP {
            get {
                return ResourceManager.GetString("CANDLE_PICKUP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Die Kerze ist zu groß und passt neben den Holzscheiten nicht in den Ofen..
        /// </summary>
        internal static string CANT_DROP_CANDLE_IN_STOVE {
            get {
                return ResourceManager.GetString("CANT_DROP_CANDLE_IN_STOVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Der Raum, den Du betreten willst ist stockdunkel. Vielleicht nimmst Du irgendeine Lichtquelle mit?.
        /// </summary>
        internal static string CANT_LEAVE_ROOM_WITHOUT_LIGHT {
            get {
                return ResourceManager.GetString("CANT_LEAVE_ROOM_WITHOUT_LIGHT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Der Ofen ist durch das Feuer so heiß geworden, dass Du lieber die Finger von der Brennkammer lässt..
        /// </summary>
        internal static string CANT_OPEN_STOVE_ON_FIRE {
            get {
                return ResourceManager.GetString("CANT_OPEN_STOVE_ON_FIRE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Die Zimmerdecke besteht aus den gleichen massiven Holzbohlen wie der Fußboden..
        /// </summary>
        internal static string CEILING {
            get {
                return ResourceManager.GetString("CEILING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Das ist der Keller..
        /// </summary>
        internal static string CELLAR {
            get {
                return ResourceManager.GetString("CELLAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bei der Truhe handelt es sich um eine massive Kiste aus dicken, naturbelassenen Brettern. Der breite Deckel bietet genug Platz, um sich darauf zu setzen. An der Vorderseite kannst Du ein Schlüsselloch erkennen..
        /// </summary>
        internal static string CHEST {
            get {
                return ResourceManager.GetString("CHEST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Es scheint sich um ein Einlassschloss zu handeln, dass den Deckel der Kiste von unten sichert. .
        /// </summary>
        internal static string CHEST_LOCK {
            get {
                return ResourceManager.GetString("CHEST_LOCK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Die Truhe ist abgeschlossen..
        /// </summary>
        internal static string CHEST_LOCKED {
            get {
                return ResourceManager.GetString("CHEST_LOCKED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Das Ofenrohr ist ein handelsübliches, schwarz lackiertes Edelstahlrohr. Es ist fest mit dem Ofen und der Wand verbunden. Und ein Tipp: eine weitere Betrachtung des Gegenstandes wird Dich nicht weiter bringen!.
        /// </summary>
        internal static string CHIMNEY {
            get {
                return ResourceManager.GetString("CHIMNEY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vielen Dank, dass Du &apos;Die Waldhütte&apos; gespielt hast..
        /// </summary>
        internal static string CLOSING {
            get {
                return ResourceManager.GetString("CLOSING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Die Brennkammer ist ein kleiner Raum, in dem das Holz verbrannt wird, um die erforderliche Energie für den Ofen zu erzeugen..
        /// </summary>
        internal static string COMBUSTION_CHAMBER {
            get {
                return ResourceManager.GetString("COMBUSTION_CHAMBER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Das gusseiserne Kochfeld ist fest mit dem Ofen verbaut und ermöglicht es, Speisen und andere Dinge zu erhitzen, sobald der Ofen befeuert wird..
        /// </summary>
        internal static string COOCKTOP_LINKEDTO {
            get {
                return ResourceManager.GetString("COOCKTOP_LINKEDTO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Das gusseiserne Kochfeld ist fest mit dem Ofen verbaut. Ist der Ofen angefeuert, wird auch die Platte heiß. Eine Temperaturregulierung gibt es nicht. Die Temperatur ist einzig und allein von dem prasselnden Feuer des Ofens abhängig..
        /// </summary>
        internal static string COOKTOP {
            get {
                return ResourceManager.GetString("COOKTOP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geschrieben von Marc Biegota..
        /// </summary>
        internal static string CREDITS {
            get {
                return ResourceManager.GetString("CREDITS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Die Tür scheint Dein Weg nach Draußen zu sein. Sie besteht aus massiven Holzbohlen, die schon die Idee zunichte machen, sie mit Gewalt öffnen zu wollen..
        /// </summary>
        internal static string DOOR {
            get {
                return ResourceManager.GetString("DOOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Du drückst die Türklinke nach unten und versuchst die Tür zu öffnen. Sie ist verschlossen und bewegt sich keinen Millimeter..
        /// </summary>
        internal static string DOOR_FIRSTLOOK {
            get {
                return ResourceManager.GetString("DOOR_FIRSTLOOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Die brennenden Scheite entwickeln schnell eine große Hitze. Damit Du Dich nicht verbrennst, schliesst Du den Ofen wieder. 
        ///Schon nach kurzer Zeit merkst Du, wie der Ofen heiß wird und sich wohlige Wärme im Raum breit macht..
        /// </summary>
        internal static string FIRE_STARTER {
            get {
                return ResourceManager.GetString("FIRE_STARTER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Der Fußboden besteht aus massiven Holzbohlen. .
        /// </summary>
        internal static string FLOOR {
            get {
                return ResourceManager.GetString("FLOOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Du bist in Freiheit!.
        /// </summary>
        internal static string FREEDOM {
            get {
                return ResourceManager.GetString("FREEDOM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Das Sichtfenster des Ofens ist zwar leicht verrußt, aber es gibt dennoch den Blick frei auf die Brennkammer..
        /// </summary>
        internal static string INSPECTION_WINDOW {
            get {
                return ResourceManager.GetString("INSPECTION_WINDOW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Der Schlüssel ist aus Eisen, ungefähr so groß, dass er gerade so auf Deine geöffnete Handfläche passt. Er sieht altmodisch, fast schon antik aus. Zumindest soweit Du das beurteilen kannst. Zumindest scheint er optisch zu dem Schloß in der Kiste zu gehören..
        /// </summary>
        internal static string IRON_KEY {
            get {
                return ResourceManager.GetString("IRON_KEY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Das Schlüsselloch ist der einzige sichtbare Hinweis auf den Schliessmechanismus der Truhe. Es ist mit einem geschnörkelten Schlüsselschild verziert und in das Schlüsselloch scheint ein recht großer Schlüssel hinein zu passen..
        /// </summary>
        internal static string KEY_HOLE {
            get {
                return ResourceManager.GetString("KEY_HOLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hm? So richtig kennst Du Dich mit sowas ja nicht aus, aber die Verzierung könnte eine typische Barock-Arbeit sein..
        /// </summary>
        internal static string KEY_HOLE_SHIELD {
            get {
                return ResourceManager.GetString("KEY_HOLE_SHIELD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Das Regal besteht eigentlich nur aus zwei Brettern, die übereinander angebracht und an den Seiten jeweils verbunden sind..
        /// </summary>
        internal static string KITCHEN_CABINET {
            get {
                return ResourceManager.GetString("KITCHEN_CABINET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Über dem Ofen hängt ein kleiner offener Küchenschrank, der genug Platz für einige Küchenutensilien bieten könnte. Viel sieht man dort allerdings nicht..
        /// </summary>
        internal static string KITCHEN_CABINET_CONTAINMENT {
            get {
                return ResourceManager.GetString("KITCHEN_CABINET_CONTAINMENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Du riechst an der mit Flüßigkeit gut gefüllten Kanne. Es scheint sich tatsächlich um Petroleum zu handeln. Das wird Dir bestimmt noch nützlich sein..
        /// </summary>
        internal static string LAMP_OIL_BUCKET {
            get {
                return ResourceManager.GetString("LAMP_OIL_BUCKET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auf dem oberen Brett steht eine Kanne mit der Aufschrift &apos;Petroleum&apos;..
        /// </summary>
        internal static string LAMP_OIL_BUCKET_CONTAINMENT {
            get {
                return ResourceManager.GetString("LAMP_OIL_BUCKET_CONTAINMENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Offensichtlich befindest Du Dich in einer Blockhütte. Alles um Dich herum, die Wände, der Boden, die Decke über Dir und ein großer Tisch, sind aus massivem Holz gefertigt. An der westlichen Wand befindet sich ein schmales Bücherregal..
        /// </summary>
        internal static string LIVINGROOM {
            get {
                return ResourceManager.GetString("LIVINGROOM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Das Fenster ist geschlossen, aber Du kannst keinen Griff oder sonst einen Mechanismus erkennen, mit dem es sich öffnen lässt. Du siehst, dass von Außen Fensterläden angebracht sind, die aktuell geschlossen sind. Diese sind so dicht, das kein Licht in den Raum dringt..
        /// </summary>
        internal static string LIVINGROOM_WINDOW {
            get {
                return ResourceManager.GetString("LIVINGROOM_WINDOW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Du hälst die Flamme an das Brennholz, doch diese ist nicht starkt genug, um es zu entzünden. Vielleicht benötigst Du einen leicht entzündlichen Gegenstand, der Dir helfen kann?.
        /// </summary>
        internal static string NO_FIRE_ACCELERATOR {
            get {
                return ResourceManager.GetString("NO_FIRE_ACCELERATOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Der Zettel ist ein Blatt aus hochwertigem Büttenpapier. Es scheint etwas darauf geschrieben zu sein..
        /// </summary>
        internal static string NOTE {
            get {
                return ResourceManager.GetString("NOTE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vorsichtig hälst Du die Flamme an das Papier, das sofort Feuer fängt. Das Blatt entwickelt beim Verbrennen die nötige Hitze, um auch die Scheite zu entfachen. Super! Das hat funktioniert!.
        /// </summary>
        internal static string NOTE_BURNED {
            get {
                return ResourceManager.GetString("NOTE_BURNED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hallo Fremder, 
        ///wir entschuldigen uns schon jetzt für die Unannehmlichkeiten und hoffen, dass Dein Schädel nicht all zu sehr von unserem speziellen Cocktail schmerzt. Sei es drum. Denn scheinbar hattest Du gestern auf unserer Party eine Menge Spaß. 
        ///Nun, jetzt wollen wir unseren Spaß! Zugegeben: etwas unfair, da Du uns ja überhaupt nicht kennst. Aber was ist schon fair?
        ///Um es kurz zu machen: bereite uns doch die Freude, Dir dabei zuzuschauen, wie Du versuchst aus diesem kleinen Gefängnis zu entkommen. 
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string NOTE_LETTER_CONTENT {
            get {
                return ResourceManager.GetString("NOTE_LETTER_CONTENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Langsam öffnest Du die Augen. Ein pochender Schmerz durchdringt Deinen Schädel. Die Mischung aus Alkohol und diverser Partydrogen scheint Dir nicht wirklich bekommen zu sein. So langsam gelingt es Dir, Deine Umgebung wahrzunehmen. Du liegst offensichtlich auf den harten Dielen eines Holzfußbodens und behäbigt setzt Du Dich auf und schaust Dich um. Irgendwo her spendet eine flackernde Lichtquelle ein spärliches Licht. Um Dich herum gibt es nichts, was Dir bekannt vorkommt. Nun stellst Du Dich hin und unsiche [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string OPENING {
            get {
                return ResourceManager.GetString("OPENING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Das Petroleum eignet sich wunderbar dafür, in eine entsprechende Lampe gefüllt zu werden. Aber auch als direkter Brandbeschleuniger kann es benutzt werden..
        /// </summary>
        internal static string PETROLEUM {
            get {
                return ResourceManager.GetString("PETROLEUM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vorsichtig hälst Du die Flamme an die mit Petroleum überschütteten Holzscheite, die sofort Feuer fangen. Das Petroleum entwickelt beim Verbrennen die nötige Hitze, um auch die Scheite zu entfachen. Super! Das hat funktioniert!.
        /// </summary>
        internal static string PETROLEUM_BURNED {
            get {
                return ResourceManager.GetString("PETROLEUM_BURNED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Die Scheite aus Buchenholz sind fein säuberlich im Ofen aufgeschichtet..
        /// </summary>
        internal static string PILE_OF_WOOD {
            get {
                return ResourceManager.GetString("PILE_OF_WOOD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Die Bretter sind aus Eichenholz, grob geschliffen und ansonsten unbehandelt..
        /// </summary>
        internal static string PLANK {
            get {
                return ResourceManager.GetString("PLANK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Das bist Du..
        /// </summary>
        internal static string PLAYER {
            get {
                return ResourceManager.GetString("PLAYER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ein Stück Dauerwurst, wahrscheinlich Salami. Es sieht schon leicht verdorben aus und Du würdest es nicht mehr essen wollen..
        /// </summary>
        internal static string SAUSAGE {
            get {
                return ResourceManager.GetString("SAUSAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auf einem der Bretter liegt, etwas verloren, ein kleines Stück Wurst..
        /// </summary>
        internal static string SAUSAGE_CONTAINMENT {
            get {
                return ResourceManager.GetString("SAUSAGE_CONTAINMENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Die Fensterläden sind von Außen geschlossen und es dringt kein Licht in den Raum hinein..
        /// </summary>
        internal static string SHUTTER {
            get {
                return ResourceManager.GetString("SHUTTER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Der Küchenherd wird mit Scheitholz befeuert und das rustikale Äußere versetzt Dich zurück in vergangene Zeiten. Der Herd besitzt eine Tür mit Sichtscheibe, die den Zugang zur Brennkammer ermöglicht. Ein Ofenrohr ist mit dem Ofen verbunden und wird durch die Holzwand nach draußen geführt. Vermutlich führt es dort in einen Kamin, der dafür sorgt, dass der Rauch gut abziehen kann..
        /// </summary>
        internal static string STOVE {
            get {
                return ResourceManager.GetString("STOVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Die Brennkammer ist geschlossen..
        /// </summary>
        internal static string STOVE_CLOSED {
            get {
                return ResourceManager.GetString("STOVE_CLOSED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An der östlichen Wand steht ein alter Ofen, der mit Holz befeuert wird. Er dient wohl gleichermaßen zum Heizen, als auch zum Kochen..
        /// </summary>
        internal static string STOVE_CONTAINMENT {
            get {
                return ResourceManager.GetString("STOVE_CONTAINMENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Du kannst deutlich erkennen, dass in der Brennkammer bereits Feuerholz liegt..
        /// </summary>
        internal static string STOVE_FIRSTLOOK {
            get {
                return ResourceManager.GetString("STOVE_FIRSTLOOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Um an die Brennkammer zu gelangen, musst Du den Ofen erst öffnen..
        /// </summary>
        internal static string STOVE_MUST_BE_OPEN {
            get {
                return ResourceManager.GetString("STOVE_MUST_BE_OPEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Die Brennkammer ist geöffnet..
        /// </summary>
        internal static string STOVE_OPEN {
            get {
                return ResourceManager.GetString("STOVE_OPEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ein massiver Holztisch. Sieht sehr schwer aus..
        /// </summary>
        internal static string TABLE {
            get {
                return ResourceManager.GetString("TABLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Die Wände bestehen aus Holzstämmen, die übereinander gestapel das eigentliche Gebäude definieren..
        /// </summary>
        internal static string WALL {
            get {
                return ResourceManager.GetString("WALL", resourceCulture);
            }
        }
    }
}
