//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LogCabin.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Descriptions {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Descriptions() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LogCabin.Resources.Descriptions", typeof(Descriptions).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Das ist der Dachboden..
        /// </summary>
        internal static string ATTIC {
            get {
                return ResourceManager.GetString("ATTIC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Das ist das Schlafzimmer..
        /// </summary>
        internal static string BEDROOM {
            get {
                return ResourceManager.GetString("BEDROOM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Du kannst {0} nicht einfach auspusten..
        /// </summary>
        internal static string BLOW_OUT_NOT_POSSIBLE {
            get {
                return ResourceManager.GetString("BLOW_OUT_NOT_POSSIBLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Die Verwandlung.
        /// </summary>
        internal static string BOOK_I {
            get {
                return ResourceManager.GetString("BOOK_I", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Krieg und Frieden.
        /// </summary>
        internal static string BOOK_II {
            get {
                return ResourceManager.GetString("BOOK_II", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to De Profundis.
        /// </summary>
        internal static string BOOK_III {
            get {
                return ResourceManager.GetString("BOOK_III", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Die Blechtrommel.
        /// </summary>
        internal static string BOOK_IV {
            get {
                return ResourceManager.GetString("BOOK_IV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Die Dreigroschenoper.
        /// </summary>
        internal static string BOOK_V {
            get {
                return ResourceManager.GetString("BOOK_V", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Du nimmst Dir wahllos eines der Bücher aus dem Regel. &quot;{0}&quot; - ein weiteres Meisterwerk der Weltliteratur. Mit einem Lächeln im Gesicht steckst Du es zurück an seinen Platz..
        /// </summary>
        internal static string BOOKS {
            get {
                return ResourceManager.GetString("BOOKS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ein altes Bücherregal aus Holz. Neben viel Staub stehen dort nur einige Bücher drin..
        /// </summary>
        internal static string BOOKSHELF {
            get {
                return ResourceManager.GetString("BOOKSHELF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An der westlichen Wand befindet sich ein schmales Bücherregal..
        /// </summary>
        internal static string BOOKSHELF_CONTAINMENT {
            get {
                return ResourceManager.GetString("BOOKSHELF_CONTAINMENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Du hälst {0} an das Papier, das sofort lichterlohn in Flammen steht. Geistesgegewärtig lässt Du es los und es schwebt, getragen durch die Hitze des Feuers, eine kurze Zeit in der Luft. Ein letztes Mal flammt das Papier noch auf, das Feuer erstirbt und ein paar unbedeutende Aschekrümel fallen auf den Boden..
        /// </summary>
        internal static string BURN_NOTE {
            get {
                return ResourceManager.GetString("BURN_NOTE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Es ist eines der Streichhölzer aus der Schachtel. Es brennt..
        /// </summary>
        internal static string BURNING_MATCH {
            get {
                return ResourceManager.GetString("BURNING_MATCH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eine große weiße Kerze, die bestimmt einige Tage brennen kann. .
        /// </summary>
        internal static string CANDLE {
            get {
                return ResourceManager.GetString("CANDLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eine Kerze verbreitet ein spärliches Licht..
        /// </summary>
        internal static string CANDLE_CONTAINMENT {
            get {
                return ResourceManager.GetString("CANDLE_CONTAINMENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Als Du die Kerze in die Hand nimmst, fühlt sie sich schwerer an, als Du vermutet hättest. Als wäre etwas im Wachs, das dort nicht hinein gehört..
        /// </summary>
        internal static string CANDLE_PICKUP {
            get {
                return ResourceManager.GetString("CANDLE_PICKUP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Die Kerze ist zu groß und passt neben den Holzscheiten nicht in den Ofen..
        /// </summary>
        internal static string CANT_DROP_CANDLE_IN_STOVE {
            get {
                return ResourceManager.GetString("CANT_DROP_CANDLE_IN_STOVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Da hier fast alles aus Holz ist, lässt Du das brennende Streichholz besser nicht fallen..
        /// </summary>
        internal static string CANT_DROP_MATCH {
            get {
                return ResourceManager.GetString("CANT_DROP_MATCH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WAS? Da sind noch andere Streichhölzer in der Schachtel. Das gäbe aber mal ein schönes Feuerwerk!.
        /// </summary>
        internal static string CANT_DROP_MATCH_IN_BOX {
            get {
                return ResourceManager.GetString("CANT_DROP_MATCH_IN_BOX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Der Raum, den Du betreten willst ist stockdunkel. Vielleicht nimmst Du irgendeine Lichtquelle mit?.
        /// </summary>
        internal static string CANT_LEAVE_ROOM_WITHOUT_LIGHT {
            get {
                return ResourceManager.GetString("CANT_LEAVE_ROOM_WITHOUT_LIGHT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Der Ofen ist durch das Feuer so heiß geworden, dass Du lieber die Finger von der Brennkammer lässt..
        /// </summary>
        internal static string CANT_OPEN_STOVE_ON_FIRE {
            get {
                return ResourceManager.GetString("CANT_OPEN_STOVE_ON_FIRE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Da Petroleum flüssig ist, kannst Du es nicht einfach nehmen..
        /// </summary>
        internal static string CANT_TAKE_PETROLEUM {
            get {
                return ResourceManager.GetString("CANT_TAKE_PETROLEUM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Die Zimmerdecke besteht aus den gleichen massiven Holzbohlen wie der Fußboden..
        /// </summary>
        internal static string CEILING {
            get {
                return ResourceManager.GetString("CEILING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Das ist der Keller..
        /// </summary>
        internal static string CELLAR {
            get {
                return ResourceManager.GetString("CELLAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Du hast nun zumindest etwas über die Umstände erfahren, aber die Identitäten der Beteiligten bleiben im Dunkeln. Ein ungutes Gefühl beschleicht Dich bei dem Gedanken, dass Du hier tatsächlich nicht entkommen könntest. Wirst Du jemals herausfinden, wer diese Leute sind und was sie wirklich umtreibt oder wirst Du für immer in der Unwissenheit gefangen sein?.
        /// </summary>
        internal static string CENTRAL_MESSAGE_UNDERSTOOD {
            get {
                return ResourceManager.GetString("CENTRAL_MESSAGE_UNDERSTOOD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bei der Truhe handelt es sich um eine massive Kiste aus dicken, naturbelassenen Brettern. Der breite Deckel bietet genug Platz, um sich darauf zu setzen. An der Vorderseite kannst Du ein Schlüsselloch erkennen..
        /// </summary>
        internal static string CHEST {
            get {
                return ResourceManager.GetString("CHEST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Die Truhe ist geschlossen..
        /// </summary>
        internal static string CHEST_CLOSED {
            get {
                return ResourceManager.GetString("CHEST_CLOSED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Du siehst außerdem eine große Holztruhe, ein Fenster und eine Eingangstür..
        /// </summary>
        internal static string CHEST_CONTAINMENT {
            get {
                return ResourceManager.GetString("CHEST_CONTAINMENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Es scheint sich um ein Einlassschloss zu handeln, dass den Deckel der Kiste von unten sichert. .
        /// </summary>
        internal static string CHEST_LOCK {
            get {
                return ResourceManager.GetString("CHEST_LOCK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Die Truhe ist abgeschlossen..
        /// </summary>
        internal static string CHEST_LOCKED {
            get {
                return ResourceManager.GetString("CHEST_LOCKED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Das Ofenrohr ist ein handelsübliches, schwarz lackiertes Edelstahlrohr. Es ist fest mit dem Ofen und der Wand verbunden. Und ein Tipp: eine weitere Betrachtung des Gegenstandes wird Dich nicht weiter bringen!.
        /// </summary>
        internal static string CHIMNEY {
            get {
                return ResourceManager.GetString("CHIMNEY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vielen Dank, dass Du &apos;Die Waldhütte&apos; gespielt hast..
        /// </summary>
        internal static string CLOSING {
            get {
                return ResourceManager.GetString("CLOSING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Die Brennkammer ist ein kleiner Raum, in dem das Holz verbrannt wird, um die erforderliche Energie für den Ofen zu erzeugen..
        /// </summary>
        internal static string COMBUSTION_CHAMBER {
            get {
                return ResourceManager.GetString("COMBUSTION_CHAMBER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Das gusseiserne Kochfeld ist fest mit dem Ofen verbunden und ermöglicht das Erhitzen von Speisen und anderen Dingen, sobald der Ofen befeuert wird..
        /// </summary>
        internal static string COOCKTOP_LINKEDTO {
            get {
                return ResourceManager.GetString("COOCKTOP_LINKEDTO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Das gusseiserne Kochfeld ist fest mit dem Ofen verbunden. Ist der Ofen angefeuert, wird auch die Platte heiß. Eine Temperaturregulierung gibt es nicht. Die Temperatur ist einzig und allein von dem prasselnden Feuer des Ofens abhängig..
        /// </summary>
        internal static string COOKTOP {
            get {
                return ResourceManager.GetString("COOKTOP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geschrieben von Marc Biegota..
        /// </summary>
        internal static string CREDITS {
            get {
                return ResourceManager.GetString("CREDITS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Die Tür scheint Dein Weg nach Draußen zu sein. Sie besteht aus massiven Holzbohlen, die schon die Idee zunichte machen, sie mit Gewalt öffnen zu wollen..
        /// </summary>
        internal static string DOOR {
            get {
                return ResourceManager.GetString("DOOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Du drückst die Türklinke nach unten und versuchst die Tür zu öffnen. Sie ist verschlossen und bewegt sich keinen Millimeter..
        /// </summary>
        internal static string DOOR_FIRSTLOOK {
            get {
                return ResourceManager.GetString("DOOR_FIRSTLOOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Es ist bereits genug Petroleum in der Lamp..
        /// </summary>
        internal static string ENOUGH_PETROLEUM_IN_LAMP {
            get {
                return ResourceManager.GetString("ENOUGH_PETROLEUM_IN_LAMP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Du willst wirklich {0} mit {1} anzünden? Wie soll das gehen?.
        /// </summary>
        internal static string FIRE_FIRE_WITH_FIRE {
            get {
                return ResourceManager.GetString("FIRE_FIRE_WITH_FIRE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Die brennenden Scheite entwickeln schnell eine große Hitze. Damit Du Dich nicht verbrennst, schliesst Du den Ofen wieder. 
        ///Schon nach kurzer Zeit merkst Du, wie der Ofen heiß wird und sich wohlige Wärme im Raum breit macht..
        /// </summary>
        internal static string FIRE_STARTER {
            get {
                return ResourceManager.GetString("FIRE_STARTER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Der Fußboden besteht aus massiven Holzbohlen. .
        /// </summary>
        internal static string FLOOR {
            get {
                return ResourceManager.GetString("FLOOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Du bist in Freiheit!.
        /// </summary>
        internal static string FREEDOM {
            get {
                return ResourceManager.GetString("FREEDOM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Der Weg in die Freiheit liegt scheinbar Richtung Süden..
        /// </summary>
        internal static string FREEDOM_DESTINATION_DESCRIPTION {
            get {
                return ResourceManager.GetString("FREEDOM_DESTINATION_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Doch die massive Holztür versperrt Dir den Weg..
        /// </summary>
        internal static string FREEDOM_LOCK_DESCRIPTION {
            get {
                return ResourceManager.GetString("FREEDOM_LOCK_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Womit möchtest Du {0} anzünden?.
        /// </summary>
        internal static string HOW_TO_DO {
            get {
                return ResourceManager.GetString("HOW_TO_DO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Das Sichtfenster des Ofens ist zwar leicht verrußt, aber es gibt dennoch den Blick frei auf die Brennkammer..
        /// </summary>
        internal static string INSPECTION_WINDOW {
            get {
                return ResourceManager.GetString("INSPECTION_WINDOW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Der Schlüssel ist aus Eisen, ungefähr so groß, dass er gerade so auf Deine geöffnete Handfläche passt. Er sieht altmodisch, fast schon antik aus. Zumindest soweit Du das beurteilen kannst. Zumindest scheint er optisch zu dem Schloß in der Kiste zu gehören..
        /// </summary>
        internal static string IRON_KEY {
            get {
                return ResourceManager.GetString("IRON_KEY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Das Schlüsselloch ist der einzige sichtbare Hinweis auf den Schliessmechanismus der Truhe. Es ist mit einem geschnörkelten Schlüsselschild verziert und in das Schlüsselloch scheint ein recht großer Schlüssel hinein zu passen..
        /// </summary>
        internal static string KEY_HOLE {
            get {
                return ResourceManager.GetString("KEY_HOLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hm? So richtig kennst Du Dich mit sowas ja nicht aus, aber die Verzierung könnte eine typische Barock-Arbeit sein..
        /// </summary>
        internal static string KEY_HOLE_SHIELD {
            get {
                return ResourceManager.GetString("KEY_HOLE_SHIELD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Da hier so ziemlich alles aus Holz ist, würde ich mir gut überlegen, was ich anzünde oder nicht. Also: nein!.
        /// </summary>
        internal static string KINDLE_ERROR_MESSAGE {
            get {
                return ResourceManager.GetString("KINDLE_ERROR_MESSAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Du reibst das Streichholz mit seinem Schwefelkopf an der entsprechenden Fläche der Schachtel und es entzündet sich..
        /// </summary>
        internal static string KINDLE_MATCH_WITH_BOX {
            get {
                return ResourceManager.GetString("KINDLE_MATCH_WITH_BOX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Du hälst die Flamme der Petroleumlampe kurz an das Streichholz und es fängt sofort an zu brennen..
        /// </summary>
        internal static string KINDLE_MATCH_WITH_LAMP {
            get {
                return ResourceManager.GetString("KINDLE_MATCH_WITH_LAMP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Das Regal besteht eigentlich nur aus zwei Brettern, die übereinander angebracht und an den Seiten jeweils verbunden sind..
        /// </summary>
        internal static string KITCHEN_CABINET {
            get {
                return ResourceManager.GetString("KITCHEN_CABINET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Über dem Ofen hängt ein kleiner, offener Küchenschrank, der Platz für einige Küchenutensilien bietet, obwohl man nicht viel darin sieht..
        /// </summary>
        internal static string KITCHEN_CABINET_CONTAINMENT {
            get {
                return ResourceManager.GetString("KITCHEN_CABINET_CONTAINMENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Die Kanne ist aus Weißblech und fasst ca. einen halben Liter Flüssigkeit..
        /// </summary>
        internal static string LAMP_OIL_BUCKET {
            get {
                return ResourceManager.GetString("LAMP_OIL_BUCKET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auf dem oberen Brett steht eine Kanne mit der Aufschrift &apos;Petroleum&apos;..
        /// </summary>
        internal static string LAMP_OIL_BUCKET_CONTAINMENT {
            get {
                return ResourceManager.GetString("LAMP_OIL_BUCKET_CONTAINMENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Du riechst an der mit Flüßigkeit gut gefüllten Kanne. Es scheint sich tatsächlich um Petroleum zu handeln. Das wird Dir bestimmt noch nützlich sein..
        /// </summary>
        internal static string LAMP_OIL_BUCKET_FIRSTLOOK {
            get {
                return ResourceManager.GetString("LAMP_OIL_BUCKET_FIRSTLOOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sie brennt gerade nicht..
        /// </summary>
        internal static string LIGHTER_OFF {
            get {
                return ResourceManager.GetString("LIGHTER_OFF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sie brennt..
        /// </summary>
        internal static string LIGHTER_ON {
            get {
                return ResourceManager.GetString("LIGHTER_ON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Offensichtlich befindest Du Dich in einer Hütte, die aus massivem Holz gebaut ist..
        /// </summary>
        internal static string LIVINGROOM {
            get {
                return ResourceManager.GetString("LIVINGROOM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Es liegt der feine Geruch von verbranntem Wachs in der Luft..
        /// </summary>
        internal static string LIVINGROOM_SMELL {
            get {
                return ResourceManager.GetString("LIVINGROOM_SMELL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Die Kerze brennt ein kleines Stückchen weiter herunter..
        /// </summary>
        internal static string LIVINGROOM_WAIT {
            get {
                return ResourceManager.GetString("LIVINGROOM_WAIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Das Fenster ist geschlossen, aber Du kannst keinen Griff oder sonst einen Mechanismus erkennen, mit dem es sich öffnen lässt. Du siehst, dass von Außen Fensterläden angebracht sind, die aktuell geschlossen sind. Diese sind so dicht, das kein Licht in den Raum dringt..
        /// </summary>
        internal static string LIVINGROOM_WINDOW {
            get {
                return ResourceManager.GetString("LIVINGROOM_WINDOW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Es ist ein handelsübliches Streichholz..
        /// </summary>
        internal static string MATCH {
            get {
                return ResourceManager.GetString("MATCH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Das Streichholz brennt bereits..
        /// </summary>
        internal static string MATCH_ALREADY_BURNING {
            get {
                return ResourceManager.GetString("MATCH_ALREADY_BURNING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Du hast bereits ein Streichholz in der Hand. Ein weiteres benötigst Du nicht..
        /// </summary>
        internal static string MATCH_ALREADY_TAKEN {
            get {
                return ResourceManager.GetString("MATCH_ALREADY_TAKEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Das Streichholz in Deiner Hand ist abgebrannt. Damit Du weiterhin Licht hast, nimmst Du ein weiteres Streichholz aus der Schachtel und zündest es an..
        /// </summary>
        internal static string MATCH_BURNED {
            get {
                return ResourceManager.GetString("MATCH_BURNED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Es brennt..
        /// </summary>
        internal static string MATCH_BURNING {
            get {
                return ResourceManager.GetString("MATCH_BURNING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In der Box befinden sich noch {0} Streichhölzer..
        /// </summary>
        internal static string MATCH_CONTAINMENT {
            get {
                return ResourceManager.GetString("MATCH_CONTAINMENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Es befinden sich keine Streichhölzer mehr in der Schachtel..
        /// </summary>
        internal static string MATCH_CONTAINMENT_EMPTY {
            get {
                return ResourceManager.GetString("MATCH_CONTAINMENT_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Das Streichholz in Deiner Hand ist zur Hälfte abgebrannt..
        /// </summary>
        internal static string MATCH_PARTIALY_BURNED {
            get {
                return ResourceManager.GetString("MATCH_PARTIALY_BURNED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dies ist eine Streichholzschachtel mit langen Zündhölzern. In ihr befinden sich noch {0} Streichhölzer..
        /// </summary>
        internal static string MATCHBOX {
            get {
                return ResourceManager.GetString("MATCHBOX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auf dem Truhenboden siehst Du eine Streichholzschachtel..
        /// </summary>
        internal static string MATCHBOX_CONTAINMENT {
            get {
                return ResourceManager.GetString("MATCHBOX_CONTAINMENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Es sind nicht mehr so viele Streichhölzer in der Schachtel. Du solltest langsam schauen, ob es nicht noch eine andere Lichtquelle gibt..
        /// </summary>
        internal static string MATCHES_RUNNING_LOW {
            get {
                return ResourceManager.GetString("MATCHES_RUNNING_LOW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Die Kerze beginnt durch die große Hitze der Platte zu schmelzen..
        /// </summary>
        internal static string MELT_CANDLE_I {
            get {
                return ResourceManager.GetString("MELT_CANDLE_I", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Das Wachs der Kerze zerfliesst ziemlich schnell und Du kannst plötzlich etwas durch die weiche, schmilzende Masse erkennen....
        /// </summary>
        internal static string MELT_CANDLE_II {
            get {
                return ResourceManager.GetString("MELT_CANDLE_II", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Das Wachs ist nun vollständig verflüssigt und fliesst hinweg. Übrig bleibt ein großer Schlüssel aus Eisen..
        /// </summary>
        internal static string MELT_CANDLE_III {
            get {
                return ResourceManager.GetString("MELT_CANDLE_III", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Du hälst die Flamme an das Brennholz, doch diese ist nicht starkt genug, um es zu entzünden. Vielleicht benötigst Du einen leicht entzündlichen Gegenstand, der Dir helfen kann?.
        /// </summary>
        internal static string NO_FIRE_ACCELERATOR {
            get {
                return ResourceManager.GetString("NO_FIRE_ACCELERATOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Es sind keine Streichhölzer mehr vorhanden..
        /// </summary>
        internal static string NO_MATCHES_LEFT {
            get {
                return ResourceManager.GetString("NO_MATCHES_LEFT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Die Lampe ist leer. Um zu funktionieren benötigt sie etwas Petroleum..
        /// </summary>
        internal static string NO_PETROLEUM_IN_LAMP {
            get {
                return ResourceManager.GetString("NO_PETROLEUM_IN_LAMP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Der Zettel ist ein Blatt aus hochwertigem Büttenpapier. Es scheint etwas darauf geschrieben zu sein..
        /// </summary>
        internal static string NOTE {
            get {
                return ResourceManager.GetString("NOTE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vorsichtig hälst Du die Flamme an das Papier, das sofort Feuer fängt. Das Blatt entwickelt beim Verbrennen die nötige Hitze, um auch die Scheite zu entfachen. Super! Das hat funktioniert!.
        /// </summary>
        internal static string NOTE_BURNED {
            get {
                return ResourceManager.GetString("NOTE_BURNED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hallo Fremder, 
        ///wir entschuldigen uns schon jetzt für die Unannehmlichkeiten und hoffen, dass Dein Schädel nicht all zu sehr von unserem speziellen Cocktail schmerzt. Sei es drum. Denn scheinbar hattest Du gestern auf unserer Party eine Menge Spaß. 
        ///Nun, jetzt wollen wir unseren Spaß! Zugegeben: etwas unfair, da Du uns ja überhaupt nicht kennst. Aber was ist schon fair?
        ///Um es kurz zu machen: bereite uns doch die Freude, Dir dabei zuzuschauen, wie Du versuchst aus diesem kleinen Gefängnis zu entkommen. 
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string NOTE_LETTER_CONTENT {
            get {
                return ResourceManager.GetString("NOTE_LETTER_CONTENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Was soll das bringen?.
        /// </summary>
        internal static string NOTHING_TO_HOLD {
            get {
                return ResourceManager.GetString("NOTHING_TO_HOLD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Langsam öffnest Du Deine Augen und spürst einen pochenden Schmerz in Deinem Kopf. Die vergangene Nacht mit Alkohol und Partydrogen scheint Dir nicht gut bekommen zu sein. Du liegst auf den harten Dielen eines Holzfußbodens und setzt Dich behäbig auf. Die spärliche Beleuchtung verrät Dir nicht, wo Du bist. Verwirrt schaust Du Dich um und versuchst, Dich zu orientieren. Du fragst Dich, wo Du bist und wie Du in diese Situation geraten konntest. Du raffst Dich auf und stehst nun auf noch etwas wackeligen Beinen [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string OPENING {
            get {
                return ResourceManager.GetString("OPENING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Es ist schon das Papier im Ofen. Das genügt für ein ordentliches Feuer!.
        /// </summary>
        internal static string PAPER_IN_STOVE {
            get {
                return ResourceManager.GetString("PAPER_IN_STOVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Petroleum eignet sich wunderbar dafür, in eine entsprechende Lampe gefüllt zu werden. Aber auch als direkter Brandbeschleuniger kann es benutzt werden..
        /// </summary>
        internal static string PETROLEUM {
            get {
                return ResourceManager.GetString("PETROLEUM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vorsichtig hälst Du die Flamme an die mit Petroleum überschütteten Holzscheite, die sofort Feuer fangen. Das Petroleum entwickelt beim Verbrennen die nötige Hitze, um auch die Scheite zu entfachen. Super! Das hat funktioniert!.
        /// </summary>
        internal static string PETROLEUM_BURNED {
            get {
                return ResourceManager.GetString("PETROLEUM_BURNED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Es ist schon ausreichend Petroleum auf dem Feuerholz vorhanden. Das genügt für ein ordentliches Feuer!.
        /// </summary>
        internal static string PETROLEUM_IN_STOVE {
            get {
                return ResourceManager.GetString("PETROLEUM_IN_STOVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eine alte und offensichtlich schon stark beanspruchte Petroleumlampe, die man als Lichtquelle gut nutzen kann. .
        /// </summary>
        internal static string PETROLEUM_LAMP {
            get {
                return ResourceManager.GetString("PETROLEUM_LAMP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Du erkennst, dass die Lampe im Moment leer ist..
        /// </summary>
        internal static string PETROLEUM_LAMP_FIRSTLOOK {
            get {
                return ResourceManager.GetString("PETROLEUM_LAMP_FIRSTLOOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Du hast sie gut mit Petroleum gefüllt..
        /// </summary>
        internal static string PETROLEUM_LAMP_FIRSTLOOK_POORED {
            get {
                return ResourceManager.GetString("PETROLEUM_LAMP_FIRSTLOOK_POORED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Die Lampe brennt bereits..
        /// </summary>
        internal static string PETROLEUM_LAMP_IS_BURNING {
            get {
                return ResourceManager.GetString("PETROLEUM_LAMP_IS_BURNING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} brennt scheinbar gar nicht..
        /// </summary>
        internal static string PETROLEUM_LAMP_NOT_BURNING {
            get {
                return ResourceManager.GetString("PETROLEUM_LAMP_NOT_BURNING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Du hälst die Flamme an den Docht der Lampe und dieser fängt sofort an zu brennen. Die Lampe ist an!.
        /// </summary>
        internal static string PETROLEUM_LAMP_SWITCH_ON {
            get {
                return ResourceManager.GetString("PETROLEUM_LAMP_SWITCH_ON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Die Scheite aus Buchenholz sind fein säuberlich im Ofen aufgeschichtet..
        /// </summary>
        internal static string PILE_OF_WOOD {
            get {
                return ResourceManager.GetString("PILE_OF_WOOD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Die Scheite aus Buchenholz sind fein säuberlich im Ofen aufgeschichtet und ordentlich mit Petroleum benetzt..
        /// </summary>
        internal static string PILE_OF_WOOD_WITH_PETROLEUM {
            get {
                return ResourceManager.GetString("PILE_OF_WOOD_WITH_PETROLEUM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Die Bretter sind aus Eichenholz, grob geschliffen und ansonsten unbehandelt..
        /// </summary>
        internal static string PLANK {
            get {
                return ResourceManager.GetString("PLANK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Das bist Du..
        /// </summary>
        internal static string PLAYER {
            get {
                return ResourceManager.GetString("PLAYER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Du füllst etwas Petroleum in die Lampe. Nun sollte man sie wieder benutzen können..
        /// </summary>
        internal static string POOR_PETROLEUM_IN_LAMP {
            get {
                return ResourceManager.GetString("POOR_PETROLEUM_IN_LAMP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Du schüttest einen Teil des Petroleums über die Scheite..
        /// </summary>
        internal static string POOR_PETROLEUM_OVER_WOOD {
            get {
                return ResourceManager.GetString("POOR_PETROLEUM_OVER_WOOD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ein Stück Dauerwurst, wahrscheinlich Salami. Es sieht schon leicht verdorben aus und Du würdest es nicht mehr essen wollen..
        /// </summary>
        internal static string SAUSAGE {
            get {
                return ResourceManager.GetString("SAUSAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auf einem der Bretter liegt, etwas verloren, ein kleines Stück Wurst..
        /// </summary>
        internal static string SAUSAGE_CONTAINMENT {
            get {
                return ResourceManager.GetString("SAUSAGE_CONTAINMENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Die Fensterläden sind von Außen geschlossen und es dringt kein Licht in den Raum hinein..
        /// </summary>
        internal static string SHUTTER {
            get {
                return ResourceManager.GetString("SHUTTER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Die Wurst riecht echt übel! Probieren würde ich sie nicht..
        /// </summary>
        internal static string SMELL_SAUSAGE {
            get {
                return ResourceManager.GetString("SMELL_SAUSAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Der Küchenherd wird mit Scheitholz befeuert und das rustikale Äußere versetzt Dich zurück in vergangene Zeiten. Der Herd besitzt eine Tür mit Sichtscheibe, die den Zugang zur Brennkammer ermöglicht. Ein Ofenrohr ist mit dem Ofen verbunden und wird durch die Holzwand nach draußen geführt. Vermutlich führt es dort in einen Kamin, der dafür sorgt, dass der Rauch gut abziehen kann..
        /// </summary>
        internal static string STOVE {
            get {
                return ResourceManager.GetString("STOVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Die Brennkammer ist geschlossen..
        /// </summary>
        internal static string STOVE_CLOSED {
            get {
                return ResourceManager.GetString("STOVE_CLOSED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ein prasselndes Feuer taucht den Raum in ein behagliches Licht und verbreitet eine wohlige Wärme..
        /// </summary>
        internal static string STOVE_CLOSED_ON_FIRE {
            get {
                return ResourceManager.GetString("STOVE_CLOSED_ON_FIRE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An der östlichen Wand steht ein alter Ofen, der mit Holz befeuert wird und sowohl zum Heizen als auch zum Kochen dient..
        /// </summary>
        internal static string STOVE_CONTAINMENT {
            get {
                return ResourceManager.GetString("STOVE_CONTAINMENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Du kannst deutlich erkennen, dass in der Brennkammer bereits Feuerholz liegt..
        /// </summary>
        internal static string STOVE_FIRSTLOOK {
            get {
                return ResourceManager.GetString("STOVE_FIRSTLOOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Um an die Brennkammer zu gelangen, musst Du den Ofen erst öffnen..
        /// </summary>
        internal static string STOVE_MUST_BE_OPEN {
            get {
                return ResourceManager.GetString("STOVE_MUST_BE_OPEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Die Brennkammer ist geöffnet..
        /// </summary>
        internal static string STOVE_OPEN {
            get {
                return ResourceManager.GetString("STOVE_OPEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bei der Pflanze handelt es sich wohl um eine Sukkulente. Sie sieht sehr saftig und wasserreich aus..
        /// </summary>
        internal static string SUCCULENT {
            get {
                return ResourceManager.GetString("SUCCULENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auf der Fensterbank steht eine Pflanze..
        /// </summary>
        internal static string SUCCULENT_CONTAINMENT {
            get {
                return ResourceManager.GetString("SUCCULENT_CONTAINMENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Der Tisch hat eine robuste und langlebige Konstruktion und sieht durch die natürlichen Maserungen und Farben des Holzes sehr elegant aus. Es wirkt durch seine Größe und Materialbeschaffenheit sehr stabil und wertig..
        /// </summary>
        internal static string TABLE {
            get {
                return ResourceManager.GetString("TABLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Im Raum befindet sich ein großer Tisch, auf dem eine brennende Kerze ein spärliches Licht verbreitet..
        /// </summary>
        internal static string TABLE_CONTAINMENT {
            get {
                return ResourceManager.GetString("TABLE_CONTAINMENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Im Raum befindet sich ein großer Tisch..
        /// </summary>
        internal static string TABLE_CONTAINMENT_WITHOUT_CANDLE {
            get {
                return ResourceManager.GetString("TABLE_CONTAINMENT_WITHOUT_CANDLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uhh! Nein. Das ekelige Stück Wurst solltest Du besser nicht in den Mund nehmen..
        /// </summary>
        internal static string TASTE_SAUSAGE {
            get {
                return ResourceManager.GetString("TASTE_SAUSAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ein widerlicher Gedanke. Das Stück ist definitiv nicht mehr für Menschen genießbar..
        /// </summary>
        internal static string TRY_TO_EAT_SAUSAGE {
            get {
                return ResourceManager.GetString("TRY_TO_EAT_SAUSAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Du kannst {0} nicht auspusten..
        /// </summary>
        internal static string UNLIGHT_NOT_POSSIBLE {
            get {
                return ResourceManager.GetString("UNLIGHT_NOT_POSSIBLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Die Wände bestehen aus Holzstämmen, die übereinander gestapel das eigentliche Gebäude definieren..
        /// </summary>
        internal static string WALL {
            get {
                return ResourceManager.GetString("WALL", resourceCulture);
            }
        }
    }
}
