//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LogCabin.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Items {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Items() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LogCabin.Resources.Items", typeof(Items).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buch|Bücher.
        /// </summary>
        internal static string BOOKS {
            get {
                return ResourceManager.GetString("BOOKS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bücherregal|Regal.
        /// </summary>
        internal static string BOOKSHELF {
            get {
                return ResourceManager.GetString("BOOKSHELF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kerze.
        /// </summary>
        internal static string CANDLE {
            get {
                return ResourceManager.GetString("CANDLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decke|Zimmerdecke.
        /// </summary>
        internal static string CEILING {
            get {
                return ResourceManager.GetString("CEILING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Holztruhe|Truhe|Kiste.
        /// </summary>
        internal static string CHEST {
            get {
                return ResourceManager.GetString("CHEST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Einlassschloss|Schloss|Schloß|Einlassschloß|Kistenschloss|Kistenschloß.
        /// </summary>
        internal static string CHEST_LOCK {
            get {
                return ResourceManager.GetString("CHEST_LOCK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ofenrohr|Rohr|Kamin.
        /// </summary>
        internal static string CHIMNEY {
            get {
                return ResourceManager.GetString("CHIMNEY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brennkammer|Kammer.
        /// </summary>
        internal static string COMBUSTION_CHAMBER {
            get {
                return ResourceManager.GetString("COMBUSTION_CHAMBER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kochfeld|Kochplatte.
        /// </summary>
        internal static string COOKTOP {
            get {
                return ResourceManager.GetString("COOKTOP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eingangstür|Tür|Holztür.
        /// </summary>
        internal static string DOOR {
            get {
                return ResourceManager.GetString("DOOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fußboden|Boden.
        /// </summary>
        internal static string FLOOR {
            get {
                return ResourceManager.GetString("FLOOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sichtfenster.
        /// </summary>
        internal static string INSPECTION_WINDOW {
            get {
                return ResourceManager.GetString("INSPECTION_WINDOW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eisenschlüssel|Metallschlüssel|Schlüssel.
        /// </summary>
        internal static string IRON_KEY {
            get {
                return ResourceManager.GetString("IRON_KEY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schlüsselloch.
        /// </summary>
        internal static string KEY_HOLE {
            get {
                return ResourceManager.GetString("KEY_HOLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schlüsselschild.
        /// </summary>
        internal static string KEY_HOLE_SHIELD {
            get {
                return ResourceManager.GetString("KEY_HOLE_SHIELD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Küchenschrank|Küchenregal|Schrank.
        /// </summary>
        internal static string KITCHEN_CABINET {
            get {
                return ResourceManager.GetString("KITCHEN_CABINET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ölkanne|Blechkanne|Kanne.
        /// </summary>
        internal static string LAMP_OIL_BUCKET {
            get {
                return ResourceManager.GetString("LAMP_OIL_BUCKET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fenster.
        /// </summary>
        internal static string LIVINGROOM_WINDOW {
            get {
                return ResourceManager.GetString("LIVINGROOM_WINDOW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blatt Papier|Zettel|Brief|Blatt|Papier.
        /// </summary>
        internal static string NOTE {
            get {
                return ResourceManager.GetString("NOTE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Petroleum|Öl|Lampenöl.
        /// </summary>
        internal static string PETROLEUM {
            get {
                return ResourceManager.GetString("PETROLEUM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Petroleumlampe|Öllampe|Lampe.
        /// </summary>
        internal static string PETROLEUM_LAMP {
            get {
                return ResourceManager.GetString("PETROLEUM_LAMP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brennholz|Scheitholz|Holzscheite|Holz|Feuerholz|Scheite|Scheit.
        /// </summary>
        internal static string PILE_OF_WOOD {
            get {
                return ResourceManager.GetString("PILE_OF_WOOD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bretter|Bohlen|Holzbohlen.
        /// </summary>
        internal static string PLANK {
            get {
                return ResourceManager.GetString("PLANK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wurstzipfel|Wurststück|Wurst|Salami.
        /// </summary>
        internal static string SAUSAGE {
            get {
                return ResourceManager.GetString("SAUSAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fensterläden|Fensterladen.
        /// </summary>
        internal static string SHUTTER {
            get {
                return ResourceManager.GetString("SHUTTER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scheiteofen|Küchenherd|Herd|Ofen|Holzofen.
        /// </summary>
        internal static string STOVE {
            get {
                return ResourceManager.GetString("STOVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Holztisch|Tisch.
        /// </summary>
        internal static string TABLE {
            get {
                return ResourceManager.GetString("TABLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wand|Wände.
        /// </summary>
        internal static string WALL {
            get {
                return ResourceManager.GetString("WALL", resourceCulture);
            }
        }
    }
}
