//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LogCabin.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class MetaData {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MetaData() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LogCabin.Resources.MetaData", typeof(MetaData).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        /// ██▓     ▒█████    ▄████     ▄████▄   ▄▄▄       ▄▄▄▄    ██▓ ███▄    █ 
        ///▓██▒    ▒██▒  ██▒ ██▒ ▀█▒   ▒██▀ ▀█  ▒████▄    ▓█████▄ ▓██▒ ██ ▀█   █ 
        ///▒██░    ▒██░  ██▒▒██░▄▄▄░   ▒▓█    ▄ ▒██  ▀█▄  ▒██▒ ▄██▒██▒▓██  ▀█ ██▒
        ///▒██░    ▒██   ██░░▓█  ██▓   ▒▓▓▄ ▄██▒░██▄▄▄▄██ ▒██░█▀  ░██░▓██▒  ▐▌██▒
        ///░██████▒░ ████▓▒░░▒▓███▀▒   ▒ ▓███▀ ░ ▓█   ▓██▒░▓█  ▀█▓░██░▒██░   ▓██░
        ///░ ▒░▓  ░░ ▒░▒░▒░  ░▒   ▒    ░ ░▒ ▒  ░ ▒▒   ▓▒█░░▒▓███▀▒░▓  ░ ▒░   ▒ ▒ 
        ///░ ░ ▒  ░  ░ ▒ ▒░   ░   ░      ░  ▒     ▒   ▒▒ ░▒░▒   ░  ▒ ░░ ░░   ░ ▒░
        ///  ░ ░  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ASCII_TITLE {
            get {
                return ResourceManager.GetString("ASCII_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Marc Biegota.
        /// </summary>
        internal static string AUTHOR {
            get {
                return ResourceManager.GetString("AUTHOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (c) by Marc Biegota 2022.
        /// </summary>
        internal static string COPYRIGHT {
            get {
                return ResourceManager.GetString("COPYRIGHT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schalte das Licht an..
        /// </summary>
        internal static string QUEST_I {
            get {
                return ResourceManager.GetString("QUEST_I", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mache Feuer..
        /// </summary>
        internal static string QUEST_II {
            get {
                return ResourceManager.GetString("QUEST_II", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Die Blockhütte - Ein Interactive Fiction Abenteuer.
        /// </summary>
        internal static string TITLE {
            get {
                return ResourceManager.GetString("TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to v0.1.4.
        /// </summary>
        internal static string VERSION {
            get {
                return ResourceManager.GetString("VERSION", resourceCulture);
            }
        }
    }
}
