//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LogCabin.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class OptionalVerbs {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal OptionalVerbs() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LogCabin.Resources.OptionalVerbs", typeof(OptionalVerbs).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Halt|Halte.
        /// </summary>
        internal static string HOLD {
            get {
                return ResourceManager.GetString("HOLD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zünde|Zünd|Zuende|Zuend|Entzünde|Entzünd|Entzuende|Entzuend.
        /// </summary>
        internal static string KINDLE {
            get {
                return ResourceManager.GetString("KINDLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schütte|Schütt|Schuette|Schuett|Kipp|Kippe|Füll|Fülle|Fuell|Fuelle|Giesse|Giess|Gieße|Gieß.
        /// </summary>
        internal static string POOR {
            get {
                return ResourceManager.GetString("POOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stelle|Stell.
        /// </summary>
        internal static string PUT {
            get {
                return ResourceManager.GetString("PUT", resourceCulture);
            }
        }
    }
}
